# Site settings
title: Stephens' home
email: stephensxub@gmail.com
description: "Copyright &copy; 2014 Stephens Xu"
baseurl: ""
url: "http://stephensxu.github.io/"
twitter_username: stephensxu1
github_username:  stephensxu

# Build settings
markdown: kramdown
permalink: pretty

pygments: true
github: [Repository metadata]

